services:
  benfordslaw-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static  # Mount static files
      - ./templates:/app/templates  # Mount template files
    environment:
      - FLASK_ENV=development
    command: python main.py
